name: jsalary_manager
description: Salary management app for Jordanian Stone
version: 1.0.6+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local DB & Paths
  sqflite: ^2.2.0
  path: ^1.8.2
  path_provider: ^2.1.1

  # ✅ Firebase Desktop-Compatible Versions
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.3
  firebase_core_desktop: ^1.0.2

  # UI & Helpers
  intl: ^0.18.1
  flutter_typeahead: ^4.1.2
  animations: ^2.0.7
  shimmer: ^3.0.0
  simple_animations: ^5.0.0+1
  uuid: ^4.1.0
  sqflite_common_ffi: ^2.3.0
  excel: ^2.0.6
  lucide_icons: ^0.257.0
  fl_chart: ^0.65.0
  lottie: ^2.6.0
  shared_preferences: ^2.2.2
  file_picker: ^10.0.0
  http: ^1.3.0
  url_launcher: ^6.2.5
  package_info_plus: 8.3.0
  open_file: ^3.5.10
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sounds/cha_ching.mp3
    - assets/sounds/money-counter.mp3




flutter_icons:
  android: false
  ios: false
  web: false
  windows:
    generate: true
    image_path: "assets/logo.png"
